import type { Course, MockTest, StudyMaterial } from "@/lib/types";

export const fallbackCourses: Course[] = [
  {
    id: "sample-course-1",
    title: "Class 10 Mathematics — Full Course",
    description: "Board-exam-focused course with concept videos, practice sets aur PYQs.",
    class: "Class 10",
    subject: "Mathematics",
    price: 999,
    is_free: false,
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-course-2",
    title: "Class 10 Science — Full Course",
    description: "Physics, Chemistry aur Biology — sab topics step by step.",
    class: "Class 10",
    subject: "Science",
    price: 999,
    is_free: false,
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-course-3",
    title: "Class 9 English Grammar Bootcamp",
    description: "Grammar rules, writing skills aur reading comprehension.",
    class: "Class 9",
    subject: "English",
    price: 499,
    is_free: false,
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-course-4",
    title: "Free Sample: Class 6 Maths Basics",
    description: "Try our teaching style for free — number systems aur basics.",
    class: "Class 6",
    subject: "Mathematics",
    price: 0,
    is_free: true,
    is_published: true,
    created_at: new Date().toISOString(),
  },
];

export const fallbackMaterial: StudyMaterial[] = [
  {
    id: "sample-mat-1",
    title: "CBSE Class 10 Maths — PYQ 2024",
    class: "Class 10",
    subject: "Mathematics",
    year: "2024",
    is_free: true,
    price: 0,
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-mat-2",
    title: "CBSE Class 10 Science — PYQ 2023",
    class: "Class 10",
    subject: "Science",
    year: "2023",
    is_free: true,
    price: 0,
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-mat-3",
    title: "Class 10 Maths — Formula Sheet",
    class: "Class 10",
    subject: "Mathematics",
    year: undefined,
    is_free: true,
    price: 0,
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-mat-4",
    title: "Class 10 Physics — Chapter-wise Notes",
    class: "Class 10",
    subject: "Physics",
    year: undefined,
    is_free: false,
    price: 149,
    is_published: true,
    created_at: new Date().toISOString(),
  },
];

export const fallbackTests: MockTest[] = [
  {
    id: "sample-test-1",
    title: "Class 10 Maths — Mock Test 1",
    class: "Class 10",
    subject: "Mathematics",
    duration_minutes: 30,
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-test-2",
    title: "Class 10 Science — Mock Test 1",
    class: "Class 10",
    subject: "Science",
    duration_minutes: 30,
    is_published: true,
    created_at: new Date().toISOString(),
  },
];
